name: GitHub Actions yaml file
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

env:
  server_key: ${{ secrets.SERVER_KEY }}

jobs:
  Salesforce-deployment-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Install Salesforce CLI plugin
        run: npm install --global @salesforce/cli

      - name: Save secret to file
        run: echo $server_key > server_key.key
        env:
          server_key: ${{ secrets.SERVER_KEY }}

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Authorize to Salesforce
        run: |
          sf org login jwt --client-id 3MVG9pRzvMkjMb6kNn45Qi9K2FN4uyLWhbBgDIWiwInPWa7Kc4S..45KzzLpdXWUYcSM5ySmgQltBvqB3_75p --jwt-key-file /home/runner/work/dreamhouse-lwc/dreamhouse-lwc/server_key.key --username pratimamaiti@nagarro.com --alias PMait
